// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrate/introspect need a direct (unpooled) connection, not the pooled
    // one the app uses at runtime via the Neon driver adapter.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
